name: Build and Upload eXMB
on:
  push:
    branches: [ qt6-cmake ]
  pull_request:
    branches: [ qt6-cmake ]
jobs:
  win32-qt630-msvc2022_64-shared:
    runs-on: windows-2022
    steps:
    - name: Checkout project source code
      uses: actions/checkout@v2
    - name: Checkout project submodules
      run: git submodule update --init --recursive
    - name: Get Qt 6.3.0
      run: |
        git clone git://code.qt.io/qt/qt5.git ..\qt630 --branch=6.3.0
    - name: Initialize Qt repositories
      run: |
        cd ..\qt630
        perl init-repository --module-subset=qtbase,qtnetworkauth,qttools,qtwebsockets
    - name: Apply qtbase patch
      run: |
        cd ..\qt630\qtbase\
        Invoke-WebRequest -Uri "https://github.com/eXhumer/qtbase-exmb/commit/9ecf9883baac67283fe1de1fb53c2983fa1b37d2.patch" -OutFile .\qtbase.patch
        git apply .\qtbase.patch
        rm .\qtbase.patch
    - name: Get OpenSSL 1.1.1o
      run: |
        git clone https://github.com/openssl/openssl.git ../openssl --origin=openssl
        cd ../openssl
        git checkout OpenSSL_1_1_1o
    - name: Get NASM 2.15.05
      run: |
        $NASM_URL = "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip"
        Invoke-WebRequest -Uri $NASM_URL -OutFile ../NASM.zip
        cd ../
        Expand-Archive NASM.zip
    - name: Configure, Build & Install OpenSSL (NASM 2.15.05 | MSVC2022-x64)
      run: |
        ${env:NASM_PATH} = (Resolve-Path ../NASM/nasm-2.15.05/).Path
        ${env:PATH} += ";${env:NASM_PATH}"
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2022_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[17.0,18.0)", "-property", "installationPath"
        $MSVC2022_INSTALL_PATH = & $VSWHERE_PATH $MSVC2022_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2022_DEVSHELL_PATH = "$MSVC2022_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2022_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2022_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        cd ..\openssl\
        mkdir ..\OpenSSL-1.1.1o\ && mkdir ..\OpenSSL-Dir\
        ${env:OPENSSL_DIR} = (Resolve-Path ..\OpenSSL-Dir).Path
        ${env:OPENSSL_PREFIX} = (Resolve-Path ..\OpenSSL-1.1.1o).Path
        perl Configure --openssldir=${env:OPENSSL_DIR} --prefix=${env:OPENSSL_PREFIX} VC-WIN64A
        nmake
        nmake install
    - name: Configure, Build & Install Qt 6.3.0 (MSVC2022-x64)
      run: |
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2022_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[17.0,18.0)", "-property", "installationPath"
        $MSVC2022_INSTALL_PATH = & $VSWHERE_PATH $MSVC2022_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2022_DEVSHELL_PATH = "$MSVC2022_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2022_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2022_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        mkdir ..\qt630-shared && cd ..\qt630-shared
        ..\qt630\configure.bat -prefix ..\Qt\6.3.0\msvc2022_64 -platform win32-msvc -release -shared
        cmake --build . --parallel
        cmake --install .
    - name: Configure, Build & Install eXMB (Qt 6.3.0 | OpenSSL 1.1.1o | MSVC2022-x64)
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      run: |
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2022_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[17.0,18.0)", "-property", "installationPath"
        $MSVC2022_INSTALL_PATH = & $VSWHERE_PATH $MSVC2022_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2022_DEVSHELL_PATH = "$MSVC2022_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2022_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2022_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        ${env:CMAKE_PREFIX_PATH} = (Resolve-Path ..\Qt\6.3.0\msvc2022_64).Path
        cmake -B ..\eXMB-build -S . -DREDDIT_CLIENT_ID="${env:REDDIT_CLIENT_ID}" -DCMAKE_INSTALL_PREFIX="..\eXMB-ReleaseOut" -DCMAKE_SYSTEM_VERSION="10.0.22000.0" -DOPENSSL_ROOT_DIR="..\OpenSSL-1.1.1o"
        cmake --build ..\eXMB-build --target ALL_BUILD --config Release --parallel
        cmake --install ..\eXMB-build
        ${env:EXMB_RELEASE_PATH} = (Resolve-Path ..\eXMB-ReleaseOut).Path
        echo "EXMB_RELEASE_PATH=${env:EXMB_RELEASE_PATH}" >> ${env:GITHUB_ENV}
    - name: Deploy Qt6 shared libraries with eXMB
      run: |
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2022_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[17.0,18.0)", "-property", "installationPath"
        $MSVC2022_INSTALL_PATH = & $VSWHERE_PATH $MSVC2022_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2022_DEVSHELL_PATH = "$MSVC2022_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2022_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2022_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        & ..\Qt\6.3.0\msvc2022_64\bin\windeployqt.exe --release --no-translations --no-compiler-runtime ..\eXMB-ReleaseOut\bin\eXMB.exe
    - name: Deploy OpenSSL shared libraries with eXMB
      run: |
        cp ..\OpenSSL-1.1.1o\bin\libcrypto-1_1-x64.dll ..\eXMB-ReleaseOut\bin
        cp ..\OpenSSL-1.1.1o\bin\libssl-1_1-x64.dll ..\eXMB-ReleaseOut\bin
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: win32-qt630-msvc2022_64-shared
        path: ${{ env.EXMB_RELEASE_PATH }}
  win32-qt630-msvc2022_64-static:
    runs-on: windows-2022
    steps:
    - name: Checkout project source code
      uses: actions/checkout@v2
    - name: Checkout project submodules
      run: git submodule update --init --recursive
    - name: Get Qt 6.3.0
      run: |
        git clone git://code.qt.io/qt/qt5.git ..\qt630 --branch=6.3.0
    - name: Initialize Qt repositories
      run: |
        cd ..\qt630
        perl init-repository --module-subset=qtbase,qtnetworkauth,qttools,qtwebsockets
    - name: Apply qtbase patch
      run: |
        cd ..\qt630\qtbase\
        Invoke-WebRequest -Uri "https://github.com/eXhumer/qtbase-exmb/commit/9ecf9883baac67283fe1de1fb53c2983fa1b37d2.patch" -OutFile .\qtbase.patch
        git apply .\qtbase.patch
        rm .\qtbase.patch
    - name: Get OpenSSL 1.1.1o
      run: |
        git clone https://github.com/openssl/openssl.git ../openssl --origin=openssl
        cd ../openssl
        git checkout OpenSSL_1_1_1o
    - name: Get NASM 2.15.05
      run: |
        $NASM_URL = "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip"
        Invoke-WebRequest -Uri $NASM_URL -OutFile ../NASM.zip
        cd ../
        Expand-Archive NASM.zip
    - name: Configure, Build & Install OpenSSL (NASM 2.15.05 | MSVC2022-x64)
      run: |
        ${env:NASM_PATH} = (Resolve-Path ../NASM/nasm-2.15.05/).Path
        ${env:PATH} += ";${env:NASM_PATH}"
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2022_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[17.0,18.0)", "-property", "installationPath"
        $MSVC2022_INSTALL_PATH = & $VSWHERE_PATH $MSVC2022_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2022_DEVSHELL_PATH = "$MSVC2022_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2022_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2022_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        cd ..\openssl\
        mkdir ..\OpenSSL-1.1.1o\ && mkdir ..\OpenSSL-Dir\
        ${env:OPENSSL_DIR} = (Resolve-Path ..\OpenSSL-Dir).Path
        ${env:OPENSSL_PREFIX} = (Resolve-Path ..\OpenSSL-1.1.1o).Path
        perl Configure --openssldir=${env:OPENSSL_DIR} --prefix=${env:OPENSSL_PREFIX} VC-WIN64A
        nmake
        nmake install
    - name: Configure, Build & Install Qt 6.3.0 (MSVC2022-x64)
      run: |
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2022_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[17.0,18.0)", "-property", "installationPath"
        $MSVC2022_INSTALL_PATH = & $VSWHERE_PATH $MSVC2022_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2022_DEVSHELL_PATH = "$MSVC2022_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2022_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2022_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        mkdir ..\qt630-static && cd ..\qt630-static
        ..\qt630\configure.bat -prefix ..\Qt\6.3.0\msvc2022_64 -platform win32-msvc -release -static
        cmake --build . --parallel
        cmake --install .
    - name: Configure, Build & Install eXMB (Qt 6.3.0 | OpenSSL 1.1.1o | MSVC2022-x64)
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      run: |
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2022_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[17.0,18.0)", "-property", "installationPath"
        $MSVC2022_INSTALL_PATH = & $VSWHERE_PATH $MSVC2022_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2022_DEVSHELL_PATH = "$MSVC2022_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2022_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2022_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        ${env:CMAKE_PREFIX_PATH} = (Resolve-Path ..\Qt\6.3.0\msvc2022_64).Path
        cmake -B ..\eXMB-build -S . -DREDDIT_CLIENT_ID="${env:REDDIT_CLIENT_ID}" -DCMAKE_INSTALL_PREFIX="..\eXMB-ReleaseOut" -DCMAKE_SYSTEM_VERSION="10.0.22000.0" -DOPENSSL_ROOT_DIR="..\OpenSSL-1.1.1o"
        cmake --build ..\eXMB-build --target ALL_BUILD --config Release --parallel
        cmake --install ..\eXMB-build
        ${env:EXMB_RELEASE_PATH} = (Resolve-Path ..\eXMB-ReleaseOut).Path
        echo "EXMB_RELEASE_PATH=${env:EXMB_RELEASE_PATH}" >> ${env:GITHUB_ENV}
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: win32-qt630-msvc2022_64-static
        path: ${{ env.EXMB_RELEASE_PATH }}
  ubuntu-qt630-gcc_64-shared:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project source code
      uses: actions/checkout@v2
    - name: Checkout project submodules
      run: git submodule update --init --recursive
    - name: Install Qt 6.3.0 build requirements
      run: |
        sudo apt-get update && sudo apt-get install build-essential libclang-11-dev libgl1-mesa-dev libssl-dev libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev ninja-build
    - name: Get Qt 6.3.0 Source Code
      run: |
        cd ../
        git clone git://code.qt.io/qt/qt5.git qt630 --branch=6.3.0
        cd ./qt630
        perl init-repository --module-subset=qtbase,qtnetworkauth,qttools,qtwebsockets
        cd ./qtbase
        wget "https://github.com/eXhumer/qtbase-exmb/commit/9ecf9883baac67283fe1de1fb53c2983fa1b37d2.patch"
        git apply 9ecf9883baac67283fe1de1fb53c2983fa1b37d2.patch
        rm 9ecf9883baac67283fe1de1fb53c2983fa1b37d2.patch
    - name: Build Qt 6.3.0
      run: |
        mkdir ../qt630-shared
        cd ../qt630-shared
        ../qt630/configure -prefix ../Qt/6.3.0/gcc_64 -platform linux-g++ -release -shared
        cmake --build . --parallel
        cmake --install .
    - name: Build eXMB
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      run: |
        CMAKE_PREFIX_PATH=../Qt/6.3.0/gcc_64 cmake -B ../eXMB-build -S . -DREDDIT_CLIENT_ID="$REDDIT_CLIENT_ID" -DCMAKE_INSTALL_PREFIX="../eXMB-ReleaseOut" -DCMAKE_SYSTEM_VERSION="10.0.22000.0"
        cmake --build ../eXMB-build --target eXMB StreamableUploader --config Release
        cmake --install ../eXMB-build
        echo "EXMB_RELEASE_PATH=$(cd ../eXMB-ReleaseOut; pwd)" >> $GITHUB_ENV
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-qt630-gcc_64-shared
        path: ${{ env.EXMB_RELEASE_PATH }}
