name: Build and Upload eXMB
on:
  push:
    branches: [ qt6-cmake ]
  pull_request:
    branches: [ qt6-cmake ]
jobs:
  build-qt622-msvc2019_64:
    runs-on: windows-latest
    steps:
    - name: Checkout project source code
      uses: actions/checkout@v2
    - name: Checkout project submodules
      run: git submodule update --init --recursive
    - name: Get Qt 6.2.2 Source Code
      run: |
        cd ..\
        git clone git://code.qt.io/qt/qt5.git qt622 --branch=6.2.2
        cd .\qt622
        perl init-repository --module-subset=qtbase,qtnetworkauth
    - name: Build Qt
      run: |
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2019_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[16.0,17.0)", "-property", "installationPath"
        $MSVC2019_INSTALL_PATH = & $VSWHERE_PATH $MSVC2019_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2019_DEVSHELL_PATH = "$MSVC2019_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2019_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2019_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        cmake -B ..\qt622-build -S ..\qt622 -DCMAKE_INSTALL_PREFIX="..\qt_622_msvc2019_64" -DQT_QMAKE_TARGET_MKSPEC="win32-msvc" -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -G Ninja
        cmake --build ..\qt622-build --parallel
        cmake --install ..\qt622-build
    - name: Build eXMB
      run: |
        $VSWHERE_PATH = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $DEV_CMD_ARGS = "-arch=amd64", "-host_arch=amd64", "-no_logo"
        $MSVC2019_VSWHERE_INSTALL_PATH_ARGS = "-products", "*", "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", "-version", "[16.0,17.0)", "-property", "installationPath"
        $MSVC2019_INSTALL_PATH = & $VSWHERE_PATH $MSVC2019_VSWHERE_INSTALL_PATH_ARGS
        $MSVC2019_DEVSHELL_PATH = "$MSVC2019_INSTALL_PATH\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Import-Module $MSVC2019_DEVSHELL_PATH
        Enter-VsDevShell -VsInstallPath "$MSVC2019_INSTALL_PATH" -DevCmdArguments ($DEV_CMD_ARGS -join " ")
        cmake -B ..\eXMB-build -S . -DCMAKE_INSTALL_PREFIX="..\eXMB-ReleaseOut" -DCMAKE_PREFIX_PATH="..\qt_622_msvc2019_64" -DCMAKE_SYSTEM_VERSION="10.0.22000.0"
        ls ..\qt_622_msvc2019_64
        cat ..\eXMB-build\CMakeFiles\CMakeOutput.log
        cmake --build ..\eXMB-build --target eXMB --config Release --parallel
        cmake --install ..\eXMB-build
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: win32-qt622-msvc2019_64
        path: ../eXMB-ReleaseOut
